-- AlterTable
ALTER TABLE `admin` ADD COLUMN `role` ENUM('ADMIN', 'CAR_OWNER', 'ORGANIZATION') NOT NULL DEFAULT 'ADMIN';

-- AlterTable
ALTER TABLE `carowner` ADD COLUMN `role` ENUM('ADMIN', 'CAR_OWNER', 'ORGANIZATION') NOT NULL DEFAULT 'CAR_OWNER';

-- AlterTable
ALTER TABLE `organization` ADD COLUMN `role` ENUM('ADMIN', 'CAR_OWNER', 'ORGANIZATION') NOT NULL DEFAULT 'ORGANIZATION';
